# This is a basic workflow to help you get started with Actions

name: Update-cloudflared

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - name: Restore cached cf-go
        id: cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/cloudflared/cloudflared/go
          key: ${{ runner.os }}-cf-go

      - name: build cf-go
        if: steps.cache.outputs.cache-hit != 'true' 
        run: |
          git clone https://github.com/cloudflare/go --depth 1
          cd go/src
          ./make.bash
          chmod +x ../bin/go

      - name: cache cf-go
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: /home/runner/work/cloudflared/cloudflared/go
          key: ${{ runner.os }}-cf-go
          restore-keys: |
            ${{ runner.os }}-cf-go
